### PR TITLE
TEIIDTOOLS-904 running the websocket over tomcat

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by shawkins** [comment]
@blafond @rareddy this took a some more playing around, but it does seem to create the endpoint of of the existing embedded tomcat instance. I can see it come up in the integration test under ws://localhost:port/teiid-ddl-language-server - where port is the standard randomly assigned tomcat port.  We should probably consider taking teiid out of the endpoint name.

**Comment by rareddy** [comment]
When you say random port because you did not assign the defined port and used 0 as to randomize right? to enable the call through the OAuth proxy we need some kind of context, it can be "/dv/lsp" or "dv-lsp" where the former would not require any changes in Syndesis Operator whereas later would need.

**Comment by shawkins** [comment]
> When you say random port because you did not assign the defined port and used 0 as to randomize right? to

No, I literally mean when running one of the IntegrationTest* classes which uses @SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)

I just meant that I verified it works.  When run normally it will be over the standard port.

The operator changes were narrowed with this pr to just naming the http port, but that can also be considered optional now.

**Comment by rareddy** [comment]
So, in the end the only question I have is do we need a separate port or can we run over existing one?

**Comment by shawkins** [comment]
I think my initial comment made this confusing.  This runs over the same port as all of the http traffic.

**Comment by rareddy** [comment]
nice :+1:

**Comment by blafond** [comment]
@shawkins So other than rebuilding DV (./tools/bin/syndesis build -m dv -d -i -f) I'll just need to discover the root URL and append the teiid-ddl-language-server ( and possibly remove teiid from it) ?

**Comment by shawkins** [comment]
> discover the root URL

Yes the root dv url now exposes that endpoint, which yes we can consider renaming.

**Pull request closed without merging**
